### ISSUE TITLE
500 Internal Server Error Exception in PDOStatement::execute()

### ISSUE THREAD

**Issue by mesutde** [Macsch15/SimPas#64]
if text short then
500 Internal Server Error
Exception in PDOStatement::execute()

why see error.

**Comment by mesutde** [comment]
can you share the sql file

**Comment by Macsch15** [comment]
Hi, you have to execute ```$ php cmd/console SyncDb``` command.

https://github.com/Macsch15/SimPas#how-to-install

**Comment by mesutde** [comment]
hi..
I don't have vps
there is only cpanel linux
I can't run a command line here
Im site.. http://cutapaste.net/
if send paste button
show error message..
500 Internal Server Error
Exception in PDOStatement::execute()

**Comment by mesutde** [comment]
> Hi, you have to execute `$ php cmd/console SyncDb` command.
> 
> https://github.com/Macsch15/SimPas#how-to-install

hi..
I don't have vps
there is only cpanel linux
I can't run a command line here
Im site.. http://cutapaste.net/
if send paste button
show error message..
500 Internal Server Error
Exception in PDOStatement::execute()

**Comment by Macsch15** [comment]
SQL:

```
CREATE TABLE `simpas_pastes` (
  `paste_id` int(11) NOT NULL,
  `unique_id` varchar(100) DEFAULT NULL,
  `time` varchar(15) DEFAULT NULL,
  `size` int(10) DEFAULT NULL,
  `length` int(10) DEFAULT NULL,
  `syntax` tinytext,
  `content` longtext,
  `ip_address` varchar(40) DEFAULT NULL,
  `raw_content` longtext,
  `title` varchar(255) DEFAULT NULL,
  `author` varchar(255) DEFAULT NULL,
  `start_from_line` int(10) DEFAULT NULL,
  `visibility` tinytext,
  `author_website` varchar(255) DEFAULT NULL,
  `short_url` varchar(255) DEFAULT NULL,
  `expire` varchar(15) DEFAULT NULL,
  `hits` int(10) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `simpas_pastes` ADD PRIMARY KEY (`paste_id`);
```

**Comment by mesutde** [comment]
> SQL:
> 
> ```
> CREATE TABLE `simpas_pastes` (
>   `paste_id` int(11) NOT NULL,
>   `unique_id` varchar(100) DEFAULT NULL,
>   `time` varchar(15) DEFAULT NULL,
>   `size` int(10) DEFAULT NULL,
>   `length` int(10) DEFAULT NULL,
>   `syntax` tinytext,
>   `content` longtext,
>   `ip_address` varchar(40) DEFAULT NULL,
>   `raw_content` longtext,
>   `title` varchar(255) DEFAULT NULL,
>   `author` varchar(255) DEFAULT NULL,
>   `start_from_line` int(10) DEFAULT NULL,
>   `visibility` tinytext,
>   `author_website` varchar(255) DEFAULT NULL,
>   `short_url` varchar(255) DEFAULT NULL,
>   `expire` varchar(15) DEFAULT NULL,
>   `hits` int(10) DEFAULT '0'
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
> 
> ALTER TABLE `simpas_pastes` ADD PRIMARY KEY (`paste_id`);
> ```


thanks..
sql insert panel  but
00 Internal Server Error
Exception in PDOStatement::execute()
show error log..

how can ı fixed.

**Comment by Macsch15** [comment]
Paste here content of **/storage/last_exception.cgi**.
You can open this file with notepad for example.

**Comment by mesutde** [comment]
/storage/last_exception.cgi
there is no file in this folder path

do you use skype or teamviewer or
If I give you cpanel information
can you spare time for me.

google hangout: mesutdemirci.ts@gmail.com
skype : gidelon@hotmail.com

**Comment by Macsch15** [comment]
Open: **library/Application/Application.php**
Find:
```php
    const ENVIRONMENT = 'prod';
```
Replace with:
```
    const ENVIRONMENT = 'dev';
```
Save and upload.

After this, you should see error message.

**Comment by mesutde** [comment]
problem solved thank you
