### ISSUE TITLE
facebook link opening error

### ISSUE THREAD

**Issue by mesutde** [Macsch15/SimPas#65]
hi..
when i share a facebok link
end of link
?fbclid...0arIzJr9vLlon4S-8wwkUKE38
auto adding
link does not open
exaple : http://cutapaste.net/paste/13809196210
facebok share : 
http://cutapaste.net/paste/13809196210?fbclid...F1bWOnpQoCS2ig2dFBowovxSU
404 Page not found

how can ı fix.

**Comment by Macsch15** [comment]
Hi,
Fix will be in 0.7 version.

For now open:
```library/Application/Routing/Routing.php```

Find:
```php
                if (preg_match('/^' . $node . '\/?$/', $this->_request, $arguments)) {
```

Replace with:
```php
                if (preg_match('/^' . $node . '\/?(.*?)$/', $this->_request, $arguments)) {
```
