### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by KevinLage** [Macsch15/SimPas#68]
After I finished the setup and rebooted the server it just shows me this screen.
![grafik](https://user-images.githubusercontent.com/43577910/96270958-d57d6d00-0fbb-11eb-9485-c0c5e7ba9235.png)

**Comment by Macsch15** [comment]
Hello, open `library/Application/Application.php` then change 
```php
const ENVIRONMENT = 'prod';
```
to
```php
const ENVIRONMENT = 'dev';
```
Then open SimPas again. This should provide to us more information about this exception. Make screenshot and send this over here.

**Comment by KevinLage** [comment]
![grafik](https://user-images.githubusercontent.com/43577910/96287770-f355cc80-0fd1-11eb-801e-4a5973d9a9dd.png)
![grafik](https://user-images.githubusercontent.com/43577910/96287796-fc469e00-0fd1-11eb-8eab-7b7c6a076b3d.png)

**Comment by Macsch15** [comment]
You must set chmod 0777 to `/storage` (recursive) directory.

**Comment by Macsch15** [comment]
```
chmod 0777 /path/to/simpas/storage -R
```
